# This is a basic workflow that is manually triggered

name: Atualizar Artigos do Space

on:
  schedule:
    - cron: '10 1 * * *'

jobs:
  update:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Atualizar os artigos
      run: |
        python ./src/atualizar_artigos_do_space.py
        
