# This is a basic workflow that is manually triggered

name: Carregar Artigos do Space

on:
  workflow_dispatch:

jobs:
  load:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Carregar os artigos
      run: |
        python ./src/carregar_artigos_do_space.py
        
